name: Deploy to KIND (Local K8s)

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to DockerHub"]  # 👈 docker-build.yml ka name yeh hi hona chahiye
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up KUBECONFIG for kind
      run: |
        mkdir -p $HOME/.kube
        kind get kubeconfig > $HOME/.kube/config

    - name: Deploy to KIND Cluster
      run: |
        kubectl apply -f diabetes.yaml

    - name: Verify Deployment Status
      run: |
        kubectl rollout status deployment/diabetes-api

    - name: Show Service Info
      run: |
        kubectl get svc diabetes-api-service
        echo "✅ Visit http://localhost:30080/docs"
