name: Build and Push Docker Image to DockerHub

on:
  # workflow_dispatch:     # Manually run karne ke liye
  push:
    branches: [main]     # Jab main branch me push ho
  pull_request:
    branches: [main]     # Jab PR create/update ho main ke against

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t diabetes-model-test:${{ github.sha }} .

    - name: Login to DockerHub (only on push)
      if: github.event_name == 'push'
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag and Push image to DockerHub (only on push)
      if: github.event_name == 'push'
      run: |
        docker tag diabetes-model-test:${{ github.sha }} iamvikramkumar/diabetes-model-demo:v1
        docker push iamvikramkumar/diabetes-model-demo:v1
