name: FastAPI CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run FastAPI health check
        run: |
          python -m uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5
          curl --fail http://localhost:8000/docs
